-- Question 1: Retrieve the total number of rentals made in the Sakila database.
select count(rental_id) from sakila.rental;

-- Question 2: Find the average rental duration (in days) of movies rented from the Sakila database.
select avg(rental_duration) from sakila.film;

-- Question 3: Display the first name and last name of customers in uppercase.
select upper(first_name),upper(last_name) from sakila.customer;

-- Question 4: Extract the month from the rental date and display it alongside the rental ID.
select month(rental_date),rental_id from sakila.rental;

-- Question 5: Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select count(rental_id),customer_id from sakila.rental group by customer_id;

-- Question 6: Find the total revenue generated by each store.
select staff_id,sum(amount) from sakila.payment group by staff_id;
-- OR --
select store_id, sum(amount) from sakila.payment p join sakila.store s on p.staff_id=s.store_id group by s.store_id;

-- Question 7: Display the title of the movie, customer's first name, and last name who rented it.
select f.title,c.first_name,c.last_name from sakila.film f join sakila.inventory i on f.film_id=i.film_id join sakila.rental r on r.inventory_id=i.inventory_id
join sakila.customer c on r.customer_id=c.customer_id;

-- Question 8: Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
select a.first_name,a.last_name from sakila.film f join sakila.film_actor fa on f.film_id=fa.film_id 
join sakila.actor a on fa.actor_id=a.actor_id where f.title="Gone with the Wind";

-- GROUP BY --

-- Question 1: Determine the total number of rentals for each category of movies.
select c.category_id,c.name, count(r.rental_id) from sakila.film f join sakila.film_category fc on f.film_id=fc.film_id 
join sakila.category c on c.category_id=fc.category_id
join sakila.inventory i on f.film_id=i.film_id  
join sakila.rental r on r.inventory_id=i.inventory_id group by c.category_id,c.name;

-- Question 2: Find the average rental rate of movies in each language.
select l.language_id,l.name, avg(rental_rate) from sakila.film f join sakila.language l on f.language_id=l.language_id group by l.language_id,l.name;

-- JOINS --

-- Question 3: Retrieve the customer names along with the total amount they've spent on rentals.
-- Note: Rental table need not to be joined as mentioned in the Hints
select c.first_name,c.last_name,sum(p.amount) from sakila.customer c
 join sakila.payment p on c.customer_id=p.customer_id group by c.customer_id;
 
-- Question 4: List the titles of movies rented by each customer in a particular city (e.g., 'London').
select c.first_name,c.last_name,ci.city,f.title from sakila.film f join sakila.inventory i on f.film_id=i.film_id
join sakila.rental r on i.inventory_id=r.inventory_id join sakila.customer c on r.customer_id=c.customer_id
join sakila.address a on c.address_id=a.address_id join sakila.city ci on a.city_id=ci.city_id group by c.customer_id,ci.city_id,f.title;

-- Advanced Joins & Group By -- 

-- Question 5: Display the top 5 rented movies along with the number of times they've been rented.
select f.title,count(r.rental_id) AS RentalCount from sakila.film f 
join sakila.inventory i on f.film_id=i.film_id 
join sakila.rental r on i.inventory_id=r.inventory_id group by f.title order by RentalCount desc limit 5;

-- Question 6: Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).

select c.first_name,c.last_name from sakila.inventory i join sakila.rental r on i.inventory_id=r.inventory_id
join sakila.customer c on r.customer_id=c.customer_id where i.store_id in (1,2)  group by c.customer_id having count(distinct i.store_id)=2 order by c.first_name;

